services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: presensi_laravel:latest
    container_name: presensi_laravel
    env_file:
      - .env
    networks:
      - presensi-net

  nginx:
    image: nginx:1.21-alpine
    container_name: presensi_nginx
    depends_on:
      - laravel
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/public:ro
    ports:
      - "80:80"
    networks:
      - presensi-net

  classifier:
    build:
      context: ./image-classifier
      dockerfile: Dockerfile
    image: presensi_classifier:latest
    container_name: presensi_flask
    # env_file:
    #   - image-classifier/.env
    networks:
      - presensi-net

networks:
  presensi-net:
    driver: bridge
