version: "3.8"

services:
  laravel:
    image: iammburg/presensi-laravel:latest
    container_name: laravel
    expose:
      - "9000"
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: presensi-pbl
      DB_USERNAME: root
      DB_PASSWORD: SiNdaruNgapainDah
    volumes:
      - laravel-public:/var/www/public
      - ./laravel.env:/var/www/.env
      - ./storage/app/public:/var/www/storage/app/public

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - laravel
    volumes:
      - ./laravel.conf:/etc/nginx/conf.d
      - laravel-public:/var/www/public
      - ./storage/app/public:/var/www/storage/app/public

  flask:
    image: iammburg/presensi-flask:latest
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      STUDENT_PHOTOS_DIR: /app/student-photos
      TEACHER_PHOTOS_DIR: /app/teacher-photos
    volumes:
      - ./student-photos:/app/student-photos
      - ./teacher-photos:/app/teacher-photos
    command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SiNdaruNgapainDah
      MYSQL_DATABASE: presensi-pbl
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
  mysql-data:
  laravel-public:
