version: '3.8'

services:
  laravel:
    image: iammburg/presensi-laravel:latest
    container_name: presensi_laravel
    expose:
      - "9000"
    depends_on:
      - flask
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: presensi-pbl
      DB_USERNAME: root
      DB_PASSWORD: SiNdaruNgapainDah

  nginx:
    image: nginx:latest
    container_name: nginx_laravel
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - laravel

  flask:
    image: iammburg/presensi-flask:latest
    container_name: presensi_flask
    ports:
      - "5000:5000"
    environment:
      STUDENT_PHOTOS_DIR: /app/student-photos
      TEACHER_PHOTOS_DIR: /app/teacher-photos
    command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SiNdaruNgapainDah
      MYSQL_DATABASE: presensi-pbl
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: http://localhost:8080/
      UPLOAD_LIMIT: 300M
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
  mysql-data:
