version: '3.8'
services:
  laravel:
    image: ghcr.io/your-org/presensi-laravel:${GIT_SHA}
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - presensi-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - laravel
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - presensi-net

  flask:
    image: ghcr.io/your-org/presensi-flask:${GIT_SHA}
    env_file:
      - image-classifier/.env.prod
    restart: unless-stopped
    networks:
      - presensi-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  presensi-net:
    driver: bridge
