version: '3.8'

services:
  laravel:
    image: iammburg/presensi-laravel:latest
    expose:
      - "9000"
    depends_on:
      - flask
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: presensi-pbl
      DB_USERNAME: root
      DB_PASSWORD: SiNdaruNgapainDah
    volumes:
      - laravel_public:/var/www/public
      - ./laravel.env:/var/www/.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - laravel_public:/var/www/public
    depends_on:
      - laravel
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  flask:
    image: iammburg/presensi-flask:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      STUDENT_PHOTOS_DIR: /app/student-photos
      TEACHER_PHOTOS_DIR: /app/teacher-photos
    command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SiNdaruNgapainDah
      MYSQL_DATABASE: presensi-pbl
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: http://localhost:8080/
      UPLOAD_LIMIT: 300M
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql-data:
  laravel_public:
