name: CI/CD to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Laravel
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest

      - name: Deploy Laravel to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest
            cd /home/${{ secrets.VPS_USER }}/app
            docker-compose -f docker-compose.prod.yml up -d laravel nginx phpmyadmin

  deploy-flask:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    continue-on-error: true
    steps:
      - name: Deploy Flask to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/presensi-flask:latest
            cd /home/${{ secrets.VPS_USER }}/app

            echo "Cleaning up old flask containers..."
            docker ps -a --filter "name=flask" --format "{{.ID}}" | xargs -r docker rm -f || true

            echo "Running updated flask container..."
            docker-compose -f docker-compose.prod.yml up -d flask
