name: CI/CD to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Laravel
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest

      - name: Deploy Laravel to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Navigating to app directory..."
            cd /home/${{ secrets.VPS_USER }}/app

            echo "Bringing down all containers safely..."
            docker-compose -f docker-compose.prod.yml down --remove-orphans || true

            echo "Pulling latest images..."
            docker-compose -f docker-compose.prod.yml pull || true

            echo "Starting only services we care about..."
            docker-compose -f docker-compose.prod.yml up -d laravel nginx phpmyadmin

      - name: Fix Laravel permissions
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Fixing Laravel permissions..."
            docker exec presensi_laravel chown -R www-data:www-data storage bootstrap/cache
            docker exec presensi_laravel chmod -R 775 storage bootstrap/cache
            docker exec presensi_laravel php artisan config:cache
            docker exec presensi_laravel php artisan route:cache
            docker exec presensi_laravel php artisan view:cache
            docker exec presensi_laravel php artisan optimize

  deploy-flask:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    continue-on-error: true
    steps:
      - name: Deploy Flask to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/app

            echo "Force remove flask container safely"
            docker-compose -f docker-compose.prod.yml rm -f flask || true

            echo "Pulling latest flask image"
            docker-compose -f docker-compose.prod.yml pull flask || true

            echo "Running fresh flask container"
            docker-compose -f docker-compose.prod.yml up -d flask

