name: CI/CD to VPS

on:
  push:
    branches:
      - main

env:
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Laravel
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:${{ github.sha }}

    - name: Build & push Flask
      run: |
        docker build -f .docker/flask/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/presensi-flask:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/presensi-flask:${{ github.sha }}

    - name: Deploy to VPS (Swarm)
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          export TAG=${{ github.sha }}
          cd /home/${{ secrets.VPS_USER }}/app
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          TAG=$TAG docker stack deploy -c docker-compose.prod.yml presensi-pbl

    - name: Fix Laravel Permissions
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "Waiting for Laravel container..."
          for i in {1..10}; do
            ID=$(docker ps --filter 'name=laravel' --filter 'name=presensi-pbl' -q | head -n1)
            if [ -n "$ID" ]; then break; fi
            echo "Waiting 5s..."
            sleep 5
          done

          if [ -z "$ID" ]; then
            echo "Laravel container not found."; exit 1
          fi

          echo "Container list (debug):"
          docker ps --format '{{.Names}} - {{.Image}}'

          echo "Fixing permissions in $ID..."
          docker exec $ID chown -R www-data:www-data storage bootstrap/cache
          docker exec $ID chmod -R 775 storage bootstrap/cache
          docker exec $ID php artisan config:cache
          docker exec $ID php artisan route:cache
          docker exec $ID php artisan view:cache
          docker exec $ID php artisan optimize
