name: CI/CD Laravel + Flask (No Downtime)

on:
  push:
    branches: [main]

env:
  TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Laravel
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:${TAG} .
        docker push ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:${TAG}

    - name: Build & Push Flask
      run: |
        docker build -f .docker/flask/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/presensi-flask:${TAG} .
        docker push ${{ secrets.DOCKER_USERNAME }}/presensi-flask:${TAG}

    - name: SSH Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/app

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          export TAG=${{ github.sha }}

          # Pull image
          docker-compose pull

          # Start new version (tanpa stop service lain)
          docker-compose up -d --build

          # Wait for Laravel to boot
          echo "Menunggu Laravel aktif..."
          sleep 10

          LARAVEL_ID=$(docker ps -qf "name=laravel")
          echo "Fixing Laravel Permissions in $LARAVEL_ID..."
          docker exec "$LARAVEL_ID" mkdir -p storage bootstrap/cache
          docker exec "$LARAVEL_ID" chown -R www-data:www-data storage bootstrap/cache || true
          docker exec "$LARAVEL_ID" chmod -R 775 storage bootstrap/cache || true
          docker exec "$LARAVEL_ID" php artisan config:cache || true
          docker exec "$LARAVEL_ID" php artisan route:cache || true
          docker exec "$LARAVEL_ID" php artisan view:cache || true

          echo "Deployment selesai TANPA downtime!"
