name: CI/CD Laravel + Flask (No Downtime)

on:
  push:
    branches: [main]

env:
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Laravel
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest

    - name: Check Laravel Assets in Container
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest ls -lah /var/www/public/assets/css || echo "❌ CSS folder tidak ada"
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/presensi-laravel:latest cat /var/www/public/assets/css/style.css || echo "❌ style.css tidak ada"

    - name: Build & Push Flask
      run: |
        docker build -f .docker/flask/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/presensi-flask:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/presensi-flask:latest

    - name: Copy docker-compose.prod.yml to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "docker-compose.prod.yml"
        target: "/home/${{ secrets.VPS_USER }}/app"

    - name: Copy entire NGINX folder to VPS (safe + overwrite)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "nginx/laravel.conf"
        target: "/home/${{ secrets.VPS_USER }}/app/nginx/"
        overwrite: true

    - name: SSH Check final nginx config path
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "==== /app/nginx/laravel.conf ===="
          cat ~/app/nginx/laravel.conf || echo "❌ laravel.conf NOT FOUND"

    - name: SSH Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e
          cd ~/app

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          echo "TAG=latest" > .env

          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d --build

          echo "⏳ Menunggu Laravel container siap..."
          timeout=60
          elapsed=0
          while ! docker exec laravel php artisan --version 2>/dev/null; do
            echo "⏳ Menunggu... (${elapsed}s)"
            sleep 2
            elapsed=$((elapsed+2))
            if [ "$elapsed" -ge "$timeout" ]; then
              echo "❌ Laravel container tidak siap setelah $timeout detik."
              exit 1
            fi
          done

          LARAVEL_ID=$(docker ps -qf "name=laravel")
          echo "🔧 Fixing Laravel Permissions in $LARAVEL_ID..."
          docker exec "$LARAVEL_ID" mkdir -p storage bootstrap/cache
          docker exec "$LARAVEL_ID" chown -R www-data:www-data storage bootstrap/cache || true
          docker exec "$LARAVEL_ID" chmod -R 775 storage bootstrap/cache || true
          docker exec "$LARAVEL_ID" php artisan config:cache || true
          docker exec "$LARAVEL_ID" php artisan route:cache || true
          docker exec "$LARAVEL_ID" php artisan view:cache || true
          docker exec "$LARAVEL_ID" php artisan optimize || true
          docker exec "$LARAVEL_ID" rm -f public/storage || true
          docker exec "$LARAVEL_ID" php artisan storage:link || true

          echo "🧾 NGINX config inside container:"
          docker exec nginx cat /etc/nginx/conf.d/laravel.conf | head -n 20 || true

          echo "♻️ Reloading NGINX to apply new config..."
          docker exec nginx nginx -s reload || docker restart nginx

          echo "✅ Laravel deployment completed!"
